### ISSUE TITLE
동아리 캘린더

### ISSUE THREAD

**Issue by sysys10** [forif-npo/forif-official#26]
**기능 요청이 어떤 문제와 관련이 있나요? 설명해 주세요.**
언제 어디서 수업이 진행되는지, 행사에 관한 정보를 부원들이 한번에 알지 못하는 불편함이 있었습니다.

**원하시는 해결책을 설명해 주세요**
포리프 웹사이트 내에 캘린더를 만들어 일정 확인이 가능하도록 하면 좋을 것 같습니다.

**고려해 보신 대안들을 설명해 주세요**
포리프 챗봇에 시간표 or 일정을 안내하는 기능 넣기

**추가 정보**
와이어프레임 (4-1) 참고
![4 1](https://github.com/user-attachments/assets/1e506544-28a6-4d16-9ada-7ef6be06c48c)
(db 스터디 쪽 참고)
https://www.notion.so/hforif/DB-ab91a88fadac4dbc8744a3a1c4558333

**Comment by standardwish** [comment]
On started
